import {it,expect} from 'vitest';
import {compileContent} from '../../src/content/index';
import {battleHarness,battleRaw} from '../fixtures/m3';
it('rejects unproved asynchronous recursion, forged producers, bad grid/spawn/charge and implicit batch fanout',()=>{
 const raw=battleRaw();const cases:unknown[]=[{...raw,gameplay:{...raw.gameplay,cellSizeWorld:1}},{...raw,gameplay:{...raw.gameplay,spawns:[{xWorld:0,yWorld:0,team:0,controller:'player'}]}},{...raw,gameplay:{...raw.gameplay,maxProjectiles:129}},{...raw,gameplay:{...raw.gameplay,actions:raw.gameplay.actions.map(a=>({...a,rechargeMs:0}))}},{...raw,ruleset:{...raw.ruleset,producers:[...raw.ruleset.producers,{id:'forged',kind:'action',maxInstances:1,rootsPerInstancePerTick:1,effects:['attack']}]}},{...raw,gameplay:{...raw.gameplay,projectiles:raw.gameplay.projectiles.map(p=>({...p,effect:'boltSpawn'}))}},{...raw,effects:raw.effects.map(e=>e.id==='boltHit'?{...e,node:{kind:'damage',formula:'boltDamage',damageType:'magic'}}:e)}];for(const content of cases)expect(compileContent(content,30).ok).toBe(false);
});
it('rejects malformed/nonfinite/oversized ingress and stale handles without authoritative mutation',()=>{
 const h=battleHarness(),hash=h.simulation.debugHash();for(const value of [null,{kind:'move'},{...Object.fromEntries(Array.from({length:10000},(_,i)=>[`bad${i}`,i]))}])expect(h.simulation.enqueue(value).outcome).toBe('rejected');expect(h.simulation.debugHash()).toBe(hash);expect(h.command('move',null,{xWorld:NaN,yWorld:0}).reason).toBe('schema');expect(h.command('cast','bolt',undefined,null,{index:0,generation:99}).reason).toBe('invalidActor');
});
it('Area saturation emits rejection, preserves existing instances, and frees slots in P0 before same-Tick release',()=>{
 const raw=battleRaw();raw.gameplay.spawns=Array.from({length:65},(_,i)=>({xWorld:-170,yWorld:0,team:0,controller:`seat${i}`}));const field=raw.gameplay.actions.find(a=>a.id==='field');if(!field)throw new Error('field');field.windupMs=0;field.castMs=0;field.recoveryMs=0;field.cooldownMs=0;field.maxCharges=2;const h=battleHarness(raw);for(const ref of h.refs)h.command('cast','field',{xWorld:-170,yWorld:0},null,ref);h.step();expect(h.simulation.observe().battle?.areas).toHaveLength(64);expect(h.debug.boundary().factDelivery.counts.find(c=>c.kind==='OperationRejected')?.count).toBe(1);expect(h.debug.boundary().facts.some(f=>f.reason==='areaQuota')).toBe(true);h.step(59);h.command('cast','field',{xWorld:-170,yWorld:0},null,h.refs[0],61);h.step();expect(h.simulation.observe().battle?.areas).toHaveLength(1);expect(h.debug.fault()).toBeNull();
});
