import {it,expect} from 'vitest';
import { FixedTick,Session } from '../../src/application/index';
import { matchId,sessionId } from '../../src/foundation/index';
import { battleHarness } from '../fixtures/m3';
function replay(fps:number){const h=battleHarness();h.command('move',null,{xWorld:0,yWorld:0},null,h.refs[0],1,{xWorld:0,yWorld:-1});h.command('cast','bolt',{xWorld:300,yWorld:0},null,h.refs[0],5);h.command('cast','field',{xWorld:110,yWorld:-90},null,h.refs[0],15);h.command('cast','dash',{xWorld:300,yWorld:-100},null,h.refs[0],30);h.command('cast','mend',undefined,null,h.refs[0],45);const clock=new FixedTick(30),hashes:string[]=[];clock.pulse(0,()=>true);for(let i=1;i<=fps*2;i++)expect(clock.pulse(i*1000/fps,()=>{h.simulation.step();hashes.push(h.simulation.debugHash());return true;}).overload).toBe(false);return {hashes,battle:h.simulation.observe().battle,delivery:h.debug.boundary().factDelivery};}
it('15/30/60/120 rendering FPS, same 30 Hz accepted gameplay stream, has identical all-Tick hashes and results',()=>{const reference=replay(60);expect(reference.hashes).toHaveLength(60);for(const fps of [15,30,120])expect(replay(fps)).toEqual(reference);});
it('pause consumes no combat Tick; resume retains reservation/release deadline and strips presentation metadata from Command',()=>{
 const h=battleHarness();let clearCount=0;const s=new Session({matchId:matchId('m3-test'),sessionId:sessionId('m3-test'),tickRate:30,mode:'empty',probeSpeedWorldPerSecond:0},h.simulation,{clearInput:()=>clearCount++,beforeTick:()=>{},completedTick:()=>{}});s.start();const request={kind:'cast' as const,payload:{action:h.catalog.document.gameplay?.actions.find(a=>a.id==='bolt')?.id??null,point:{xWorld:300,yWorld:0},direction:{xWorld:0,yWorld:0},target:null},sampleId:123};expect(s.submit(request)?.outcome).toBe('queued');s.frame(0);s.frame(34);expect(s.observation.battle?.units[0]?.reserved).toBe(15);s.pause('user');s.frame(100000);expect(s.debug().tick).toBe(1);s.releaseReason('user');expect(s.resume()).toBe(true);s.frame(100001);s.frame(100101);expect(s.debug().tick).toBe(4);expect(s.observation.battle?.units[0]?.reserved).toBe(0);expect(s.observation.battle?.units[0]?.resource).toBe(185);expect(clearCount).toBe(1);
});
