import fs from 'node:fs';
import { expect,it } from 'vitest';
import { WORK_KEYS } from '../../src/contracts/index';
import { battleHarness,battleRaw } from '../fixtures/m3';
function prove(h:ReturnType<typeof battleHarness>){const b=h.debug.boundary(),c=h.catalog.certificate,proof=b.capacity.scope==='startup'?c.startup:c.tick,limit=b.capacity.scope==='startup'?c.startupLimit:c.limit,profile=b.capacity.scope==='startup'?h.profile.startup:h.profile.capacity;for(const key of WORK_KEYS){expect(b.capacity.tick[key],key).toBeLessThanOrEqual(proof[key]);expect(proof[key],key).toBeLessThanOrEqual(limit[key]);expect(limit[key],key).toBeLessThanOrEqual(profile[key]);}for(const root of b.capacity.roots){const p=c.roots.find(p=>p.effect===root.effect);if(!p)throw new Error(root.effect);for(const key of WORK_KEYS)expect(root.work[key],`${root.effect}.${key}`).toBeLessThanOrEqual(p.work[key]);}expect(b.capacity.rootCount).toBeLessThanOrEqual(c.rootCount);expect(b.capacity.tick.scans).toBe(Object.values(b.capacity.scanKinds).reduce((a,b)=>a+b,0));expect(b.factDelivery.produced).toBe(b.factDelivery.consumed);expect(h.debug.fault()).toBeNull();}
it('certifies 454 startup, simultaneous actions, 128 sweeps x 326 targets, 64 Areas and CC expiry',()=>{
 const raw=battleRaw();raw.gameplay.obstacles=[];const health=raw.resources.find(r=>r.id==='health'),maximum=raw.attributes.find(a=>a.id==='maxHealth');if(!health||!maximum)throw new Error('health');health.initial=100000;maximum.base=100000;raw.gameplay.spawns=Array.from({length:454},(_,i)=>({xWorld:i<128?-400:100,yWorld:0,team:i<128?0:1,controller:`seat${i}`}));
 raw.gameplay.projectiles[0]={...raw.gameplay.projectiles[0],id:'bolt',speedWorldPerSecond:30000,radiusWorld:5,lifetimeMs:1000,hits:'multi',relation:'enemy',effect:'boltHit',sourcePolicy:'impactAttributesContinueAfterDeath'};
 const field=raw.gameplay.actions.find(a=>a.id==='field');if(!field)throw new Error('field');field.windupMs=100;field.castMs=0;field.rangeWorld=1000;
 const h=battleHarness(raw);prove(h);const startup=h.debug.boundary().capacity;
 for(let i=0;i<454;i++)expect(h.command('cast',i<128?'bolt':i<192?'field':'mend',{xWorld:i>=128&&i<192?-400:100,yWorld:0},null,h.refs[i]).outcome).toBe('queued');
 h.step(4);prove(h);const b=h.debug.boundary();expect(b.capacity.producers.find(p=>p.id==='m3.projectile')?.roots).toBe(128);expect(b.capacity.producers.find(p=>p.id==='m3.area')?.roots).toBe(64);expect(b.factDelivery.counts.find(c=>c.kind==='DamageResolved')?.count).toBe(128*326+64*128);
 h.step(18);prove(h);expect(h.debug.boundary().factDelivery.counts.find(c=>c.kind==='ModifierExpired')?.count).toBe(326*8);fs.mkdirSync('reports',{recursive:true});fs.writeFileSync('reports/m3-capacity-joint.json',JSON.stringify({status:'PASS',scope:'independently compiled 454-unit M3 joint fixture; not representative performance',certificate:h.catalog.certificate,profile:h.profile,startup,releaseTick:b.capacity,expiryTick:h.debug.boundary().capacity,releaseFacts:b.factDelivery,expiryFacts:h.debug.boundary().factDelivery,dimensions:{units:454,actionsCompleting:454,projectiles:128,projectileTargetsEach:326,areas:64,CCExpiring:326*8},scanConservation:true,noTruncation:true},null,2)+'\n');h.simulation.dispose();
},120000);
it('overlaps projectile/Area Hook Replacement with inline CC cancellation in the same certified root',()=>{
 const raw=battleRaw();const slow=raw.gameplay.actions.find(a=>a.id==='mend');if(!slow)throw new Error('mend');slow.windupMs=1000;raw.gameplay.spawns[1]={xWorld:-95,yWorld:0,team:1,controller:'target'};
 const content={...raw,modifiers:[...raw.modifiers,{id:'replace',durationMs:3000,maxInstancesPerEntity:1,contributions:[],tags:[],control:'none',deathSaveHealth:null,pulse:null,end:null,hooks:[{id:'replaceDamage',stage:'pre',match:'damage',priority:1,maxTriggersPerRootTarget:1,action:{kind:'replace',effect:'boltHit'}}]}],effects:[...raw.effects,{id:'giveReplace',node:{kind:'targets',selector:'primary',child:{kind:'applyStatus',modifier:'replace'}}}],ruleset:{...raw.ruleset,producers:raw.ruleset.producers.map(p=>({...p,effects:[...p.effects,'giveReplace']}))}};
 const h=battleHarness(content);h.simulation.enqueue({matchId:h.config.matchId,controllerId:'fixture',sequence:1,targetTick:1,actorRef:h.refs[0],kind:'debugEffect',effect:'giveReplace',producer:'fixture',targets:[h.refs[1]]});h.step();
 h.command('cast','mend',{xWorld:-95,yWorld:0},null,h.refs[1]);h.command('cast','bolt',{xWorld:200,yWorld:0});h.step(4);prove(h);expect(h.simulation.observe().battle?.units[1]?.reserved).toBe(0);expect(h.debug.boundary().facts.some(f=>f.kind==='ActionInterrupted')).toBe(true);expect(h.debug.boundary().facts.some(f=>f.kind==='OperationReplaced')).toBe(true);
});
it('certifies command ingress, bounded history eviction and replay membership independently of Tick work',()=>{
 const h=battleHarness();for(let n=0;n<600;n++){h.command('move',null,undefined,null,h.refs[0],h.debug.boundary().tick+1,{xWorld:0,yWorld:0});const a=h.debug.commandCapacity(),c=h.catalog.certificate;if(!a)throw new Error('command capacity');for(const key of WORK_KEYS){expect(a.tick[key],key).toBeLessThanOrEqual(c.command[key]);expect(c.command[key]).toBeLessThanOrEqual(c.commandLimit[key]);expect(c.commandLimit[key]).toBeLessThanOrEqual(h.profile.command[key]);}expect(a.tick.scans).toBe(Object.values(a.scanKinds).reduce((a,b)=>a+b,0));h.step();}expect(h.debug.fault()).toBeNull();
});
