export interface DocumentCurrentState {
    readonly schema: string;
    readonly version: string;
    readonly phase: string;
    readonly baseCommit: string;
    readonly candidate: string;
    readonly productReview: string;
    readonly documentationReview: string;
    readonly softwareExitFinal: string;
    readonly toolbarBlocker: string;
    readonly currentAndroidBlocker: string;
    readonly androidGapRetest: string;
    readonly overall: string;
    readonly androidOverall: string;
    readonly formalAB: string;
    readonly thermalBattery20min: string;
    readonly secondTier4GB: string;
    readonly portrait: string;
    readonly tickRate: number;
    readonly tickRateStatus: string;
    readonly modeA: string;
    readonly modeB: string;
    readonly modeC: string;
    readonly pushed: boolean;
    readonly deployed: boolean;
    readonly androidAcceptanceResumed: boolean;
    readonly nextPhaseStarted: boolean;
    readonly contentHash: string;
    readonly certificate: string;
    readonly m2Certificate: string;
    readonly jointCertificate: string;
    readonly toolbarFixVersion: string;
    readonly nextPhase: string;
}
export const CURRENT_STATE_DOCUMENTS: Readonly<Record<string, string>>;
export function withoutHistoricalRecords(text: string): string;
export function renderCurrentStateHeader(title: string, status: DocumentCurrentState): string;
export function validateCurrentStateSource(metadata: {version: string; mobaPhase: string}, status: DocumentCurrentState): void;
export function validateCurrentStateDocuments(files: ReadonlyMap<string, string>, metadata: {version: string; mobaPhase: string}, status: DocumentCurrentState): number;
